### ISSUE TITLE
Determine who will meet with Peter

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/save-seistool#3]
@uaedan I wanted to loop you in on setting up a useful first meeting, to ensure access to code and folks are going to be able to make progress.

**Comment by ProximaDas** [comment]
I've sent out a mail to Peter to set up a meeting tomorrow (Friday). More updates to follow soon!

**Comment by uaedan** [comment]
O.K. I'll stay posted.

**Comment by uaedan** [comment]
Peter tells me there will be a meeting at 11:00 tomorrow.  I should be able to make it, so see you then.

**Comment by davclark** [comment]
Hey all - it's good to close issues when they're done!
