### ISSUE TITLE
Language implementation of the tool

### ISSUE THREAD

**Issue by ProximaDas** [BIDS-collaborative/save-seistool#4]
Discuss options about the language in which seistool is to be re-implemented.

**Comment by davclark** [comment]
What's the link to the python tool? I was recommending you look at:
- [Bokeh](http://bokeh.pydata.org/) - targets python as the main backend, but supports other languages
- The last time I checked, [C3](http://c3js.org/) was the easiest / best community around high-level D3 charts (but not for streaming data - for that, Epoch is nice)

**Comment by ProximaDas** [comment]
Bokeh and C3 are web-browser based tools. We would need something that can support a standalone window, I think.

**Comment by ProximaDas** [comment]
We decided to use ObsPy - which is a Python library for handling seismic data for reading miniSEED files. Bokeh is being currently used to render this information in a web browser. We are looking at how to use `bokeh-server` to implement this in a server-client model.
