### ISSUE TITLE
Cannot access FTP location for seistool

### ISSUE THREAD

**Issue by ProximaDas** [BIDS-collaborative/save-seistool#5]
The below site asks for login credentials at ftp://ncedc.org/outgoing/lombard/seistool/seistool.tar.gz
Bob, could you help us?

**Comment by dougneuhauser** [comment]
user: ftp
password:  your email address
- Doug N

On 10/6/15 5:34 PM, Proxima DasMohapatra wrote:

> The below site asks for login credentials at ftp://ncedc.org/outgoing/lombard/seistool/seistool.tar.gz
> Bob, could you help us?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/BIDS-collaborative/save-seistool/issues/5.

## 

Doug Neuhauser                  University of California, Berkeley
doug@seismo.berkeley.edu        Berkeley Seismological Laboratory
Office: 510-642-0931            215 McCone Hall # 4760
Fax:    510-643-5811            Berkeley, CA  94720-4760
Remote: 530-752-5615 (Wed,Fri)

**Comment by uaedan** [comment]
Thanks Doug!

**Comment by ProximaDas** [comment]
Thanks Doug, I tried that, but now I see a blank window:
![screen shot 2015-10-08 at 11 08 20 am](https://cloud.githubusercontent.com/assets/1112875/10375368/fb411246-6dac-11e5-8364-4ee61a01995e.png)

**Comment by uaedan** [comment]
Proxima,  Please contact Peter Lombard for these questions.
He's not on Git, but you have is phone and his e-mail is:
lombard@seismo.berkeley.edu

**Comment by ProximaDas** [comment]
I got it, thanks!
